development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: postgres
  password: admin

test:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: postgres
  password: admin

production:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: postgres
  password: admin
